config/routes.rb
Rails.application.routes.draw do
  resources :cart, only: [ :create, :destroy]
  resources :products, only: [ :index, :show ]
  scope "/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "success", to: "checkout#success", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
  end
  root to: "products#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :price_cents, :description, presence: true
  validates :price_cents, numericality: { only_integer: true }

  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :initialize_session
  helper_method :cart

  private

  def initialize_session
    session[:cart] ||= []
  end

  def cart
    Product.find(session[:cart])
  end

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :get_product, only: [ :create, :destroy ]

  def create
    unless session[:cart].include?(@product.id)
      session[:cart] << @product.id
      flash[:notice] = "#{@product.name} was added to the cart."
    end

    redirect_to root_path
  end

  def destroy
    if session[:cart].include?(@product.id)
      session[:cart].delete(@product.id)
      flash[:notice] = "#{@product.name} was removed form the cart."
    end

    redirect_to root_path
  end

  private

  def get_product
    product_id = params[:id].to_i
    @product = Product.find(product_id)
  end

end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  # POST, so product_id will be in the POST payload!
  def create
    # Here we are going to create a Stripe session then
    # redirect the user to the checkout page
    # Fetch the product in question!
    product = Product.find(params[:product_id])

    if product.nil?
      redirect_to root_path
      return
    end

    session = Stripe::Checkout::Session.create(
      payment_method_types: ["card"],
      success_url: checkout_success_url,
      cancel_url: checkout_cancel_url,
      mode: "payment",
      line_items: [
        price_data: {
          currency: "cad",
          product_data: {
            name: product.name,
            description: product.description,
          },
          unit_amount: product.price_cents
        },
        quantity: 1
      ]
    )

    redirect_to session.url, allow_other_host: true
  end

  def success
    # We go here if the payment succeeded!
  end

  def cancel
    # Something went wrong!
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/create.html.erb
<h1>Cart#create</h1>
<p>Find me in app/views/cart/create.html.erb</p>

app/views/cart/destroy.html.erb
<h1>Cart#destroy</h1>
<p>Find me in app/views/cart/destroy.html.erb</p>

app/views/checkout/cancel.html.erb
<h1>Something went wrong!</h1>

app/views/checkout/success.html.erb
<h1>Yay we took your money!!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Shopping For Stuff" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <link rel="stylesheet" href="https://unpkg.com/mvp.css">
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <nav>
        <ul>
          <li>
            Cart
            <% if cart.present? %>
              <sup> <%= cart.size %> </sup>
              <ul>
                <% cart.each do |product| %>
                  <li>
                    <%= button_to '❌', cart_path(product), method: :delete %> <%= product.name %>
                  </li>
                <% end %>
              </ul>
            <%end%>
          </li>
        </ul>
      </nav>
      <h1><%= link_to "Buy Our Stuff", root_path %></h1>
      <h3>Make Us Rich</h3>
    </header>
    <main>
      <% flash.each do |type, msg| %>
        <div>
          <%= msg %>
        </div>
      <% end %>
      <%= yield %>
    </main>
    <footer>
      <hr>
      <p><span>🐐</span> Goats in Coats <span>🧥</span> - Copywrong <%= Time.current.year %></p>
    </footer>
  </body>
</html>

app/views/products/_product.html.erb
  <aside>
    <% if product.image.present? %>
      <p><%= image_tag product.image.variant(resize_to_limit: [285, 285]).processed  %></p>
    <% end %>
    <h3><%= link_to product.name, product %></h3>
    <p>Price: <%= number_to_currency product.price_cents / 100.0 %></p>
    <p><%= product.description %></p>
    <% if cart.include? product %>
      <%= button_to cart_path(product), method: :delete do %>
        Remove from cart
        <% end %>
    <% else %>
      <%= form_with url: cart_index_path do %>
        <%= hidden_field_tag(:id, product.id) %>
        <%= button_tag "Add to cart"%>
      <% end %>
    <% end %>
  </aside>

app/views/products/index.html.erb
<section>
  <%= render @products %>
</section>

app/views/products/show.html.erb
<section>
  <%= render @product %>
</section